name: toktik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  animate_do: ^5.1.0
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/